### ISSUE TITLE
Give core dependencies

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give-ConvertKit#4]
## Issue Overview
When Give is deactivated or is not updated to the minimum version requirement, we need to be sure that the plugin deactivates.

## Expected Behavior
Plugin will deactivate with helpful message if requirements are not met to run plugin.

## Current Behavior
The plugin stays activated with no message.

## Possible Solution
Provide message and helpful links.

## Steps to Reproduce
1. Have both Give+ add-on active
2. Deactivate Give
3. The add-ons will stay active

## Todos
- [x] Implement admin notice functionality
- [x] Implement deactivation functionality
- [x] Test min version requirement
- [x] Test Give active requirement
